### ISSUE TITLE
FdiGenerator 使用 Python3 执行报错：ImportError: No module named 'jdcal'

### ISSUE THREAD

**Issue by zxjsdp** [zxjsdp/bioinfo-scripts#9]
可能与 `library.zip` 中的 `openpyxl` 为 Python2 对应的版本有关。

```
$ python3 fdi_generator.py
Traceback (most recent call last):
  File "fdi_generator.py", line 13, in <module>
    import openpyxl
  File "library.zip/openpyxl/__init__.py", line 28, in <module>
  File "library.zip/openpyxl/workbook/__init__.py", line 5, in <module>
  File "library.zip/openpyxl/workbook/workbook.py", line 7, in <module>
  File "library.zip/openpyxl/worksheet/__init__.py", line 4, in <module>
  File "library.zip/openpyxl/worksheet/worksheet.py", line 34, in <module>
  File "library.zip/openpyxl/cell/__init__.py", line 4, in <module>
  File "library.zip/openpyxl/cell/cell.py", line 30, in <module>
  File "library.zip/openpyxl/utils/datetime.py", line 12, in <module>

ImportError: No module named 'jdcal'
```

**Comment by zxjsdp** [comment]
已修复。

在 library.zip 中将 `openpyxl` 的依赖：`jdcal` 和 `et_xmlfile` 加了进来。
